version: "3"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/home/selenium/tests
    links:
      - selenium
      - novnc

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - "8081:8081"
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome:123.0
    shm_size: 2g
    environment:
      - SE_VNC_NO_PASSWORD=true
      - SCREEN_WIDTH=1800
      - SCREEN_HEIGHT=960
    ports:
      - "4444:4444"
      - "5900:5900"
